name 'ip_historian'
maintainer 'Tim Corwin'
maintainer_email 'timothy.corwin@ge.com'
license 'all_rights'
description 'Installs/Configures Proficy historian'
long_description 'Installs/Configures Proficy historian 6.0'
version '0.1.0'

depends 's3_get'
depends 'windows'